In [ ]:
Exercise 2
This method will flip the x and y coordinates in the coords array.

param coords
A numpy array of bounding box coordinates with shape [n,5] in format: :

[[x11, y11, x12, y12, classid1],
 [x21, y21, x22, y22, classid2],
 ...
 [xn1, yn1, xn2, yn2, classid3]]
return
The new numpy array where the x and y coordinates are flipped.

This method is part of a series of debugging exercises. Each Python method of this series contains bug that needs to be found.

1   Can you spot the obvious error?
2   After fixing the obvious error it is still wrong, how can this be fixed?

The example demonstrates the issue. The returned swapped_coords are expected to have swapped x and y coordinates in each of the rows.

In [ ]:
# You can copy this code to your personal pipeline project or execute it here.
def swap(coords: np.ndarray):
    """
    This method will flip the x and y coordinates in the coords array.

    :param coords: A numpy array of bounding box coordinates with shape [n,5] in format:
        ::

            [[x11, y11, x12, y12, classid1],
             [x21, y21, x22, y22, classid2],
             ...
             [xn1, yn1, xn2, yn2, classid3]]

    :return: The new numpy array where the x and y coordinates are flipped.

    **This method is part of a series of debugging exercises.**
    **Each Python method of this series contains bug that needs to be found.**

    | ``1   Can you spot the obvious error?``
    | ``2   After fixing the obvious error it is still wrong, how can this be fixed?``

    >>> import numpy as np
    >>> coords = np.array([[10, 5, 15, 6, 0],
    ...                    [11, 3, 13, 6, 0],
    ...                    [5, 3, 13, 6, 1],
    ...                    [4, 4, 13, 6, 1],
    ...                    [6, 5, 13, 16, 1]])
    >>> swapped_coords = swap(coords)

    The example demonstrates the issue. The returned swapped_coords are expected to have swapped
    x and y coordinates in each of the rows.
    """
    coords[:, 0], coords[:, 1], coords[:, 2], coords[:, 3], = coords[:, 1], coords[:, 1], coords[:, 3], coords[:, 2]
    return coords

In [ ]:
import numpy as np
coords = np.array([[10, 5, 15, 6, 0],
                   [11, 3, 13, 6, 0],
                   [5, 3, 13, 6, 1],
                   [4, 4, 13, 6, 1],
                   [6, 5, 13, 16, 1]])
swapped_coords = swap(coords)

In [ ]:
# metohod 1.
# flip
# change the structure

import numpy as np
coords = np.array([[[10, 5], [15, 6], 0],
                   [[11, 3], [13, 6], 0],
                   [[5, 3], [13, 6], 1],
                   [[4, 4], [13, 6], 1],
                   [[6, 5],[ 13, 16], 1]])
swapped_coords = swap(coords)

In [ ]:
# metohod 1-1 test
# flip
# reference https://numpy.org/doc/stable/reference/generated/numpy.flip.html

import numpy as np

# test 2-1
#A = [  [  [0, 1], [2, 3]  ], [  [4, 5], [6, 7]  ]]
#print(np.flip(A, 2))

# test 2-2
"""
A = np.array([[[10, 5], [15, 6]],
                   [[11, 3], [13, 6]],
                   [[5, 3], [13, 6]],
                   [[4, 4], [13, 6]],
                   [[6, 5],[ 13, 16]]])
                   
print(np.flip(A, 2))

"""
A = np.array([[[10, 5], [15, 6], 0],
                   [[11, 3], [13, 6], 0],
                   [[5, 3], [13, 6], 1],
                   [[4, 4], [13, 6], 1],
                   [[6, 5],[ 13, 16], 1]])

print(np.flip(A, 2))        # AxisError: axis 2 is out of bounds for array of dimension 2

In [ ]:
# metohod 1-2 test
# flip testing

A = np.arange(8).reshape((2,2,2))
A
array(  [  [  [0, 1], [2, 3]  ], [  [4, 5], [6, 7]  ]  ]  )

np.flip(A, 0)  # flip(m, 0) is equivalent to flipud(m).  # Flip an array vertically (axis=0).
array([ [[4, 5],[6, 7]],[[0, 1],[2, 3]] ])

np.flip(A, 1)  # flip(m, 1) is equivalent to fliplr(m).  # Flip an array horizontally (axis=1).
array([[[2, 3],[0, 1]],[[6, 7],[4, 5]]])

np.flip(A)
array([[[7, 6],[5, 4]],[[3, 2],[1, 0]]])

np.flip(A, (0, 2))
array([[[5, 4],[7, 6]],[[1, 0],[3, 2]]])

A = np.random.randn(3,4,5)
np.all(np.flip(A,2) == A[:,:,::-1,...])
True

In [1]:
# metohod 2.
# a,b = b,a

import numpy as np
coords = np.array([[10, 5, 15, 6, 0],
                                       [11, 3, 13, 6, 0],
                                       [5, 3, 13, 6, 1],
                                       [4, 4, 13, 6, 1],
                                       [6, 5, 13, 16, 1]])

def swap(coords):
    coord = 0
    while coord < len(coords):
        coords[coord][0], coords[coord][1] = coords[coord][1], coords[coord][0]
        coords[coord][2], coords[coord][3] = coords[coord][3], coords[coord][2]
        coord += 1;
        return coords

swapped_coords = swap(coords)

print(swapped_coords)


[[ 5 10  6 15  0]
 [11  3 13  6  0]
 [ 5  3 13  6  1]
 [ 4  4 13  6  1]
 [ 6  5 13 16  1]]


In [2]:
# metohod 2-1 test
# a,b = b,a
# https://stackoverflow.com/questions/14836228/is-there-a-standardized-method-to-swap-two-variables-in-python

import numpy as np
coords = np.array([[10, 5, 15, 6, 0], [6, 5, 13, 16, 1]])

coord = 0
while coord < len(coords):
    coords[coord][0], coords[coord][1] = coords[coord][1], coords[coord][0]
    coords[coord][2], coords[coord][3] = coords[coord][3], coords[coord][2]
    coord += 1;

print(coords)

[[ 5 10  6 15  0]
 [ 5  6 16 13  1]]


In [49]:
# metohod 3
# Call by Value

import numpy as np
coords = np.array([[10, 5, 15, 6, 0],
                   [11, 3, 13, 6, 0],
                   [5, 3, 13, 6, 1],
                   [4, 4, 13, 6, 1],
                   [6, 5, 13, 16, 1]])

def swap(coords):
    coords_temp = np.copy(coords)
    coords[:, 0], coords[:, 1], coords[:, 2], coords[:, 3] = coords_temp[:, 1], coords_temp[:, 0], coords_temp[:, 3], coords_temp[:, 2]
    return coords

swapped_coords = swap(coords)
print(swapped_coords)

[[ 5 10  6 15  0]
 [ 3 11  6 13  0]
 [ 3  5  6 13  1]
 [ 4  4  6 13  1]
 [ 5  6 16 13  1]]
